name: diarynotes
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  file_manager: ^1.0.2
  on_audio_query: ^2.9.0
  connectivity_plus: ^5.0.2
  rflutter_alert: ^2.0.7
  photo_manager: ^2.8.1
  audioplayers: ^5.2.1
  audio_video_progress_bar: ^2.0.1
  share_plus: ^7.2.1
  awesome_notifications: ^0.8.2
  flutter_sound: ^9.2.13
  fl_chart: ^0.64.0
  flutter_exit_app: ^1.1.2
  device_info_plus: ^9.1.1
  #  extended_text: ^11.1.0
  #  flutter_box_transform: ^0.4.2
  #  keyboard_attachable: ^2.1.0
  #  screenshot: ^2.1.0
  #  flutter_dropdown_alert: ^1.0.7
  #  flutter_svg: ^1.1.6
  #  dotted_border: ^2.1.0
  #  pdf: ^3.10.7
  #  flutter_font_picker: ^1.4.0
  #  theme_manager: ^2.0.2
  #  super_bullet_list: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  archive:
  card_swiper: ^3.0.1
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  pattern_lock: ^2.0.0
  pin_code_fields: ^8.0.1
  flutter_pin_code_widget: ^0.1.0
  local_auth: ^2.1.7
  http: ^1.1.0
  path_provider: ^2.1.1
  fluttertoast: ^8.2.2
  flutter_neat_and_clean_calendar: ^0.3.14+32
  responsive_sizer: ^3.2.0
  syncfusion_flutter_charts: ^23.1.42
  flex_color_scheme: ^7.3.1
  objectbox: ^2.3.1
  objectbox_generator: ^2.3.1
  build_runner: ^2.4.6
  objectbox_flutter_libs: ^2.3.1
  url_launcher: ^6.2.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  video_player: ^2.8.1
  flutter_drawing_board: ^0.5.0
  file_picker: ^6.1.1
  #  flutter_image_compress: ^2.1.0
  #  story_painter: ^0.0.4
#  page_transition: ^2.1.0
#  flutter_email_sender: ^6.0.2
#  finger_painter: ^1.1.0
#  gradients: ^0.1.1+2
#  simple_ripple_animation: ^0.0.7
#  syncfusion_flutter_calendar: ^23.1.41
#  giffy_dialog: ^2.0.0+2
#  googleapis_auth: ^1.4.1
#  google_sign_in: ^6.1.5
#  googleapis: ^11.4.0
#  flutter_app_lock: ^3.0.0
#  flutter_slider_drawer: ^2.1.3
#  flutter_lints: ^2.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/bulletList/
      - assets/emojis/CatEmoji/
      - assets/emojis/loosetittokemoji/
      - assets/emojis/pikachuemoji/
      - assets/emojis/StickerEmoji/
      - assets/emojis/tiktokemoji/
      - assets/emojis/UnicornEmoji/
      - assets/locale/
      - assets/ThemeImage/
      - assets/images/DrawImages/
      - assets/ThemeImage/ThemeBackgroundDemo/


  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
#   - family: Schyler
#     fonts :
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
   - family: Avenir
     fonts:
       - asset: assets/fonts/avenir/Avenir-Next-Condensed.ttf
         style: normal
   - family: Baskerville
     fonts:
       - asset: assets/fonts/Baskerville/baskvl.ttf
         style: normal
   - family: Bodoni
     fonts:
       - asset: assets/fonts/bodoni/Bodoni-Bold-Cyrillic.ttf
         style: normal
   - family: Didot
     fonts:
       - asset: assets/fonts/didot/Didot-Regular.ttf
         style: normal
   - family: Frutiger
     fonts:
       - asset: assets/fonts/frutiger/FTB.ttf
         style: normal
   - family: Garamond
     fonts:
       - asset: assets/fonts/garamond/CormorantGaramond-Regular.ttf
         style: italic
   - family: Georgia
     fonts:
       - asset: assets/fonts/georgia/Georgia.ttf
         style: normal
   - family: Montserrat
     fonts:
       - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
         style: normal
   - family: Thenewyorktimes
     fonts:
       - asset: assets/fonts/thenewyorktimes/NewYorkTimes.ttf
         style: normal
   - family: GreatVibes
     fonts:
       - asset: assets/fonts/greatvibes/GreatVibes-Regular.ttf
         style: normal
   - family: Roboto
     fonts:
       - asset: assets/fonts/roboto/Roboto-Regular.ttf
         style: normal
   - family: Timesnewroman
     fonts:
       - asset: assets/fonts/timesnewroman/times-new-roman.ttf
         style: normal
   - family: GoodDog
     fonts:
       - asset: assets/fonts/gooddog/GOODDC__.TTF
         style: normal
   - family: Quicksand
     fonts:
       - asset: assets/fonts/quicksand/Quicksand_Bold_Oblique.otf
         style: normal
   - family: Pacifico
     fonts:
       - asset: assets/fonts/pacifico/Pacifico.ttf
         style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
